---

- name: Ensure {{ duplicacy_secret_file_path }}
  ansible.builtin.file:
    path: "{{ duplicacy_secret_file_path }}"
    state: directory
    mode: o-rwx

- name: Ensure secret file {{ _duplicacy_secret_file_name }}
  ansible.builtin.template:
    src: secret.j2
    dest: "{{ duplicacy_secret_file_path }}/{{ _duplicacy_secret_file_name }}"
    force: "{{ duplicacy_secret_file_force }}"
    mode: o-rwx

...
