---

- name: Ensure "{{ duplicacy_path }}"
  ansible.builtin.file:
    path: "{{ duplicacy_path }}"
    state: directory
    mode:  o-rwx

- name: Ensure "{{ duplicacy_path }}/bin"
  ansible.builtin.file:
    path: "{{ duplicacy_path }}/bin"
    state: directory
    mode:  o-rwx

- name: Print ansible_machine
  ansible.builtin.debug:
    msg: "ansible_machine: {{ ansible_machine }}"

- name: Ensure url snippet machine x64
  ansible.builtin.set_fact:
    _duplicacy_url_snippet_machine: 'x64'
  when: ansible_machine == 'x86_64'

- name: Ensure url snippet machine 
  ansible.builtin.set_fact:
    _duplicacy_url_snippet_machine: 'arm64'
  when: ansible_machine == 'aarch64'

- name: Ensure install duplicacy
  ansible.builtin.get_url:
    url: "https://github.com/gilbertchen/duplicacy/releases/download/v{{ duplicacy_version }}/duplicacy_linux_{{ _duplicacy_url_snippet_machine }}_{{ duplicacy_version }}"
    dest: "{{ duplicacy_path }}/bin/duplicacy"
    mode: ug+x,o-rwx

- name: Ensure working directory
  ansible.builtin.file:
    path: "{{ duplicacy_working_directory }}"
    state: directory
    mode:  o-rwx

- name: Ensure init script
  ansible.builtin.template:
    src:  duplicacy-init.sh.j2
    dest: "{{ duplicacy_init_script_file }}"
    mode: ug+x,o-rwx

- name: Ensure backup script
  ansible.builtin.template:
    src:  duplicacy-backup.sh.j2
    dest: "{{ duplicacy_backup_script_file }}"
    mode: ug+x,o-rwx

- name: Ensure prune script
  ansible.builtin.template:
    src:  duplicacy-prune.sh.j2
    dest: "{{ duplicacy_prune_script_file }}"
    mode: ug+x,o-rwx

- name: Ensure restore script
  ansible.builtin.template:
    src:  duplicacy-restore.sh.j2
    dest: "{{ duplicacy_restore_script_file }}"
    mode: ug+x,o-rwx

- name: Ensure backup schedule
  ansible.builtin.cron:
    name:      duplicacy backup
    job:       "{{ duplicacy_backup_script_file }}"
    cron_file: ansible-duplicacy-backup
    user:      "{{ duplicacy_backup_schedule_user }}"
    hour:      "{{ duplicacy_backup_schedule_hour }}"
    minute:    "{{ duplicacy_backup_schedule_minute }}"
    day:       "{{ duplicacy_backup_schedule_day }}"
    weekday:   "{{ duplicacy_backup_schedule_weekday }}"
    month:     "{{ duplicacy_backup_schedule_month }}"
  when: duplicacy_schedule

- name: Ensure prune schedule
  ansible.builtin.cron:
    name:      duplicacy prune
    job:       "{{ duplicacy_prune_script_file }}"
    cron_file: ansible-duplicacy-prune
    user:      "{{ duplicacy_prune_schedule_user }}"
    hour:      "{{ duplicacy_prune_schedule_hour }}"
    minute:    "{{ duplicacy_prune_schedule_minute }}"
    day:       "{{ duplicacy_prune_schedule_day }}"
    weekday:   "{{ duplicacy_prune_schedule_weekday }}"
    month:     "{{ duplicacy_prune_schedule_month }}"
  when: duplicacy_schedule

...

