---

- name: Check storage backend
  ansible.builtin.fail:
    msg: Storage backend '{{ duplicacy_storage_backend }}' not supported
  when: not duplicacy_storage_backend in duplicacy_storage_backends

- name: Check action
  ansible.builtin.fail:
    msg: Action '{{ duplicacy_action }}' not supported
  when: not duplicacy_action in duplicacy_actions

- name: include set facts
  include_tasks: duplicacy_set_facts.yml
  when: duplicacy_action == 'install'

- name: Include install tasks
  include_tasks: duplicacy_install.yml
  when: duplicacy_action == 'install'

- name: Ensure duplicacy init
  ansible.builtin.command:
    cmd: "{{ duplicacy_init_script_file }}"
  args:
    creates: "{{ duplicacy_working_directory }}/.duplicacy/preferences"
  when: duplicacy_action == 'install'

- name: Include pre and post script tasks
  include_tasks: duplicacy_pre_post.yml
  when: duplicacy_action == 'install'

- name: Ensure duplicacy backup
  ansible.builtin.command:
    cmd: "{{ duplicacy_backup_script_file }}"
  when: duplicacy_backup_immediately
  
...
